### ISSUE TITLE
复现精度

### ISSUE THREAD

**Issue by Godaddy-xie** [jkhu29/Deblurring-by-Realistic-Blurring#1]
请问同学复现到了论文提到的精度吗？

**Comment by jkhu29** [comment]
PSNR在29低于原论文，SSIM可以刷到0.93
同时这版代码WGAN有点bug，我有时间修一下

**Comment by jkhu29** [comment]
> 请问同学复现到了论文提到的精度吗？

目前在文章所提到数据集上已达到文章精度，我会在几天后将相关模型文件上传
代码应该没有问题，可以自行修改train.sh以及相关参数，有问题可以邮件联系，关闭该issues
