### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by rusher2020** [jkhu29/Deblurring-by-Realistic-Blurring#3]
Hi.  I have a question
There is no dataset_make.py file in the dataset make folder, only tfrecord_make.py, I wonder how to use it.

**Comment by jkhu29** [comment]
Hi! 
Please use `tfrecord_make.py `, like 
```shell
python tfrecord_make.py --mode motion-cycle
```

I am fixing the code for the tfrecord generation, but I haven't finished it yet because I'm preparing for my final exams recently.

About tfrecord files in pytorch, you can see [this](https://github.com/vahidk/tfrecord).

**Comment by rusher2020** [comment]
Thank you. I wish i can see your final result asap :)
