### ISSUE TITLE
代码环境搭建问题

### ISSUE THREAD

**Issue by YouYuanHui** [jkhu29/Deblurring-by-Realistic-Blurring#5]
同学你好，我也最近看了这篇paper，可我不知道官方的代码怎么才能运行……能否告知下环境搭建的要求与代码运行的步骤啊？万分感谢了。

**Comment by jkhu29** [comment]
官方的只有test，环境应该就是常规的pytorch torchvision，下载了pretrain param之后 sh test.sh即可

**Comment by YouYuanHui** [comment]
emmm我环境好像搭好了，但不知道该怎么样实现这个项目，
比如不知道模糊的图像放哪里，运行后生成的清晰图像又在会出现在哪……
官方的test.sh里的注释我没看明白（
# Change the path of datasets in options/test/test.json
# Deblurred images will be saved in ../results）
test.json这个文件里的路径我不知道该怎么改……

**Comment by YouYuanHui** [comment]
emmm我环境好像搭好了，但不知道该怎么样实现这个项目，
比如不知道模糊的图像放哪里，运行后生成的清晰图像又在会出现在哪……
官方的test.sh里的注释我没看明白（
Change the path of datasets in options/test/test.json
Deblurred images will be saved in ../results）
test.json这个文件里的路径我不知道该怎么改……

**Comment by jkhu29** [comment]
options/test/test.json 为存放test dataset的路径，具体的请翻一翻 test.py 里面的实现，具体 python 如何生成 json 文件，网上有许多教程，可以查找一下

**Comment by YouYuanHui** [comment]
欸我还是整不明白，是我太菜了……话说是不是得在linux操作系统下操作啊？

**Comment by jkhu29** [comment]
请在官方repo提这些issue，如果对本repo没有疑问烦请关闭该issue
